import type { Effect, Keyword, ReplacementDef, StaticEffectDef, TriggerDef } from './definition.js';

/**
 * The closed vocabulary the engine implements. Card-script validation checks every op, trigger, static
 * effect, replacement and keyword against these lists so a script can never reference something the
 * interpreter would ignore.
 */
export const EFFECT_OPS: readonly Effect['op'][] = [
  'damage',
  'gainLife',
  'loseLife',
  'setLife',
  'draw',
  'discard',
  'mill',
  'counter',
  'destroy',
  'destroyAll',
  'exileAll',
  'bounceAll',
  'sacrificeAll',
  'damageEach',
  'exile',
  'moveZone',
  'bounce',
  'sacrifice',
  'tap',
  'untap',
  'createToken',
  'addCounters',
  'removeCounters',
  'pump',
  'grantAbility',
  'loseAbilities',
  'setPT',
  'gainControl',
  'search',
  'shuffle',
  'scry',
  'surveil',
  'addMana',
  'preventDamage',
  'regenerate',
  'fight',
  'attach',
  'extraTurn',
  'sequence',
  'forEach',
  'forEachPlayer',
  'if',
  'may',
  'unless',
  'delayedTrigger',
  'createEffect',
  'choose',
  'winGame',
  'loseGame',
  'bind',
  'reveal',
  'putOnTopOfLibrary',
  'noop',
];

/** Ops that parse but are not executed yet (they resolve as no-ops); scripts using them are `partial`. */
export const UNIMPLEMENTED_OPS: readonly Effect['op'][] = ['copySpell', 'transformTargetsTo'];

export const TRIGGERS: readonly (TriggerDef['on'] | 'nextEndStep' | 'nextUpkeep')[] = [
  'etb',
  'ltb',
  'dies',
  'cast',
  'attacks',
  'blocks',
  'becomesBlocked',
  'dealsDamage',
  'dealtDamage',
  'upkeep',
  'draw',
  'endStep',
  'beginCombat',
  'landfall',
  'counterPlaced',
  'sacrificed',
  'tapped',
  'lifeGain',
  'discard',
  'nextEndStep',
  'nextUpkeep',
];

export const STATIC_EFFECTS: readonly StaticEffectDef['type'][] = [
  'pt',
  'setPT',
  'switchPT',
  'addAbility',
  'loseAbility',
  'addType',
  'setTypes',
  'removeType',
  'setColor',
  'addColor',
  'control',
  'cantAttack',
  'cantBlock',
  'cantBeBlocked',
  'cantBeBlockedBy',
  'doesntUntap',
  'mustAttack',
  'costReduction',
  'costIncrease',
  'cantCast',
  'cantActivate',
  'maxHandSize',
  'extraLandDrop',
  'playerCantGainLife',
  'noMaxLoyaltyActivations',
  'preventDamage',
  'cantBeTargeted',
];

export const REPLACEMENTS: readonly ReplacementDef['event'][] = [
  'etb',
  'dies',
  'damage',
  'draw',
  'lifeGain',
  'counterPlaced',
  'tokenCreated',
];

export const KEYWORDS: readonly (Keyword | 'protection' | 'ward')[] = [
  'flying',
  'first strike',
  'double strike',
  'deathtouch',
  'haste',
  'hexproof',
  'indestructible',
  'lifelink',
  'menace',
  'reach',
  'trample',
  'vigilance',
  'defender',
  'flash',
  'shroud',
  'split second',
  'cant be countered',
  'protection',
  'ward',
];
